version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - './web/_site:/var/www/html'
      - './images/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - 80:80
  jekyll:
    build:
      context: ./images/jekyll
      dockerfile: Dockerfile
    volumes:
      - './web:/data'
  autopull:
    build:
      context: ./images/autopull
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - './web/:/app/site'
